### ISSUE TITLE
`release` does not play nicely with sbt-ci-release

### ISSUE THREAD

**Issue by note** [softwaremill/sbt-softwaremill#103]
I've recently upgraded sbt-softwaremill in my project from 1.9.15 to 2.0.3. At the same moment, I moved from travis-ci to github-actions.

The migration went quite smoothly but I noticed one thing about `release`. Here's the example of failed release: https://github.com/note/dhallj-magnolia/runs/2108182237?check_suite_focus=true

To release the above I ran `release` and it created tag `v0.1.3-M2` while changing version in `version.sbt` to `0.1.3-SNAPSHOT`. It seems like sbt-ci-release correctly categorized it as a tagged release (look for `Tag push detected, publishing a stable release` in job's output) but then it actually uses `0.1.3-SNAPSHOT` as a version.

I am not sure but I guess taking the version from sbt vs from tag is the difference between sbt-ci-release and previously used sbt-release. With that line of thinking I proceeded with such steps:

```
// set version in version.sbt to 0.1.3-M5 and commit the change
git tag -a v0.1.3-M5 -m "Release v0.1.3-M5"                                                                                                                              22:59:29
git push origin v0.1.3-M5
```

And this one worked well as you can see here: https://github.com/note/dhallj-magnolia/actions/runs/652269012

If all that is correct then `release` probably should be rewritten to reflect for that. For example, it can create create 2 commits instead of one, with the first one setting version in `version.sbt` to version being released, and the second doing all versions bump ups to the next version. Then if the first commit is getting tagged it should work fine.

**Comment by adamw** [comment]
Ah! Sorry for not documenting this properly :)

So with the new version, you shouldn't have a `version.sbt` file. The version is deduced from git tags & current state, and uses https://github.com/dwijnand/sbt-dynver

That way the git tags are the only source & the source of truth when it comes to versions

**Comment by note** [comment]
@adamw Thanks for your quick response! I see, I will try it out in the evening and if it works for me I will close the issue.

I guess it will affect only people migrating from `1.x` line so probably no need to put it into docs, maybe just to changelog / migration guide. Leaving it up to you :)
