### ISSUE TITLE
Overriding `sonatypeCredentialHost` may be needed for many users

### ISSUE THREAD

**Issue by note** [softwaremill/sbt-softwaremill#167]
I've been fighting for some time with configuring a new release job just to discover that plugin sets:

```sonatypeCredentialHost := "s01.oss.sonatype.org"```

This however will not work for users created before the sonatype migration. Seems like those 2 sonatype instances are separate so your user is either on one or on another. So in my case, the crucial point was:

```
sonatypeCredentialHost := "oss.sonatype.org"
```

Otherwise I was getting `403: Forbidden`

**Comment by adamw** [comment]
Sorry for the trouble! I've added the appropriate information to the readme. I'll also create a proper release and add the information there.

**Comment by note** [comment]
@adamw Thanks! I think adding a note in README is the best that can be done
